@baseUrl = http://localhost:8080
@cookie = XSRF-TOKEN=74150c76-ff1a-4702-a6a5-f7861341a0d0;_sid=34433DF08B89C4CA76AA60F3FAFEDC51

### Portfolio summary
# @no-cookie-jar
GET {{baseUrl}}/api/portfolio/summary
Cookie: {{cookie}}

### Portfolio performance
# @no-cookie-jar
GET {{baseUrl}}/api/portfolio/performance
Cookie: {{cookie}}
