@baseUrl = http://localhost:8080
@cookie = XSRF-TOKEN=74150c76-ff1a-4702-a6a5-f7861341a0d0;_sid=34433DF08B89C4CA76AA60F3FAFEDC51

### Public auth ping
GET {{baseUrl}}/api/auth/ping

### Protected transactions ping
# @no-cookie-jar
GET {{baseUrl}}/api/transactions/ping
Cookie: {{cookie}}

### Protected current user
# @no-cookie-jar
GET {{baseUrl}}/api/transactions/current-user
Cookie: {{cookie}}
