@baseUrl = http://localhost:8080
@accessToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhMjA3YzQwNS01NTc1LTRjMjAtOTE5MS1hMmZlN2JlOGIxOWQiLCJlbWFpbCI6ImpvaW50LnN0ZWYyMDEyQGdtYWlsLmNvbSIsImlhdCI6MTc3MTU3ODg3MiwiZXhwIjoxNzcxNTc5NzcyfQ.5EFj_2ehb3qlF6tHiuyRC5p3AX7SpE8OLvWB7N9HnYo
@assetId = 11111111-1111-1111-1111-111111111111
@exchangeId = 33333333-3333-3333-3333-333333333333

### List transactions
GET {{baseUrl}}/api/transactions
Authorization: Bearer {{accessToken}}

### Buy transaction
POST {{baseUrl}}/api/transactions/buy
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "assetId": "{{assetId}}",
  "exchangeId": "{{exchangeId}}",
  "grossAmount": 0.1,
  "feeAmount": 0.0005,
  "feeCurrency": "BTC",
  "unitPriceUsd": 45000.0,
  "transactionDate": "2026-02-17T10:00:00Z"
}
### Buy transaction2
POST {{baseUrl}}/api/transactions/buy
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "assetId": "64550529-dc7d-45ee-9c31-28056debb553",
    "exchangeId": "dddddddd-dddd-dddd-dddd-dddddddddddd",
    "grossAmount": "1.32",
    "feeAmount": "0.1",
    "feeCurrency": "USD",
    "unitPriceUsd": "4.878",
    "transactionDate": null
}
### Buy transaction3
POST {{baseUrl}}/api/transactions/buy
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "assetId": "11111111-1111-1111-1111-111111111111",
    "exchangeId": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
    "grossAmount": "10",
    "feeAmount": "0.01",
    "feeCurrency": "BTC",
    "unitPriceUsd": "50000",
    "transactionDate": null
}

### Buy transaction4
POST {{baseUrl}}/api/transactions/buy
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "assetId": "64550529-dc7d-45ee-9c31-28056debb553",
    "exchangeId": "dddddddd-dddd-dddd-dddd-dddddddddddd",
    "feeAmount": "0.02498",
    "feePercentage": "0.001",
    "feeCurrency": "TON",
    "unitPriceUsd": "1.513",
    "transactionDate": null,
    "grossAmount": "24.98",
    "usdAmount": null,
    "inputMode": "COIN_AMOUNT"
}
### Sell transaction4
POST {{baseUrl}}/api/transactions/buy
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "assetId": "64550529-dc7d-45ee-9c31-28056debb553",
    "exchangeId": "dddddddd-dddd-dddd-dddd-dddddddddddd",
    "feeAmount": "0.055910040000000008",
    "feePercentage": "0.001",
    "feeCurrency": "USD",
    "unitPriceUsd": "2",
    "transactionDate": null,
    "grossAmount": 27.95502
}

### Sell transaction
POST {{baseUrl}}/api/transactions/sell
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "assetId": "{{assetId}}",
  "exchangeId": "{{exchangeId}}",
  "grossAmount": 0.05,
  "feeAmount": 0.0002,
  "feeCurrency": "BTC",
  "unitPriceUsd": 47000.0,
  "transactionDate": "2026-02-17T11:00:00Z"
}
